name: CI/CD Pipeline

on:
 push:
  branches: [main, develop]
 pull_request:
  branches: [main, develop]

env:
 NODE_VERSION: "18.x"
 PRISMA_VERSION: "6.12.0"

jobs:
 # Lint and test both frontend and backend
 test:
  name: Test and Lint
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Node.js
     uses: actions/setup-node@v4
     with:
      node-version: ${{ env.NODE_VERSION }}

   - name: Install root dependencies
     run: npm ci

   - name: Install frontend dependencies
     run: npm run install:frontend

   - name: Install backend dependencies
     run: npm run install:backend

   - name: Setup Prisma
     run: |
      cd backend
      npx prisma generate --schema=../prisma/schema.prisma

   - name: Lint frontend
     run: |
      cd frontend
      npx eslint src --max-warnings 0 || echo "Linting completed with warnings"

   - name: Type check frontend
     run: |
      cd frontend
      npx tsc --noEmit

   - name: Test frontend
     run: npm run test:frontend
     env:
      CI: true

   - name: Test backend
     run: npm run test:backend
     env:
      CI: true
      DATABASE_URL: "file:./test.db"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

 # Build and deploy frontend to Vercel
 deploy-frontend:
  name: Deploy Frontend to Vercel
  runs-on: ubuntu-latest
  needs: test
  if: github.ref == 'refs/heads/main'

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Node.js
     uses: actions/setup-node@v4
     with:
      node-version: ${{ env.NODE_VERSION }}

   - name: Install frontend dependencies
     run: npm run install:frontend

   - name: Build frontend
     run: npm run build:frontend
     env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

   - name: Deploy to Vercel
     uses: amondnet/vercel-action@v25
     with:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      working-directory: ./frontend
      vercel-args: "--prod"

 # Build and deploy backend to Render
 deploy-backend:
  name: Deploy Backend to Render
  runs-on: ubuntu-latest
  needs: test
  if: github.ref == 'refs/heads/main'

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Node.js
     uses: actions/setup-node@v4
     with:
      node-version: ${{ env.NODE_VERSION }}

   - name: Install backend dependencies
     run: npm run install:backend

   - name: Setup Prisma
     run: |
      cd backend
      npx prisma generate --schema=../prisma/schema.prisma

   - name: Build backend
     run: npm run build:backend

   - name: Deploy to Render
     uses: johnbeynon/render-deploy-action@v1.0.0
     with:
      service-id: ${{ secrets.RENDER_SERVICE_ID }}
      api-key: ${{ secrets.RENDER_API_KEY }}

 # Database migrations
 migrate-database:
  name: Run Database Migrations
  runs-on: ubuntu-latest
  needs: [test, deploy-backend]
  if: github.ref == 'refs/heads/main'

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Node.js
     uses: actions/setup-node@v4
     with:
      node-version: ${{ env.NODE_VERSION }}

   - name: Install backend dependencies
     run: npm run install:backend

   - name: Run database migrations
     run: |
      cd backend
      npx prisma migrate deploy --schema=../prisma/schema.prisma
     env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

 # Security and dependency checks
 security:
  name: Security Checks
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Node.js
     uses: actions/setup-node@v4
     with:
      node-version: ${{ env.NODE_VERSION }}

   - name: Install dependencies
     run: |
      npm ci
      npm run install:frontend
      npm run install:backend

   - name: Run npm audit
     run: |
      npm audit --audit-level=moderate || echo "Audit completed with warnings"
      cd frontend && npm audit --audit-level=moderate || echo "Frontend audit completed with warnings"
      cd ../backend && npm audit --audit-level=moderate || echo "Backend audit completed with warnings"

   - name: Check for outdated dependencies
     run: |
      echo "Frontend outdated packages:"
      cd frontend && npm outdated || true
      echo "Backend outdated packages:"
      cd ../backend && npm outdated || true

 # Performance and bundle analysis
 analyze:
  name: Bundle Analysis
  runs-on: ubuntu-latest
  needs: test
  if: github.ref == 'refs/heads/main'

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Node.js
     uses: actions/setup-node@v4
     with:
      node-version: ${{ env.NODE_VERSION }}

   - name: Install frontend dependencies
     run: npm run install:frontend

   - name: Build frontend with analysis
     run: |
      cd frontend
      npm run build
      npx @next/bundle-analyzer
     env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

   - name: Upload bundle analysis
     uses: actions/upload-artifact@v4
     with:
      name: bundle-analysis
      path: frontend/.next/analyze/
