name: Pull Request Checks

on:
 pull_request:
  branches: [main, develop]

env:
 NODE_VERSION: "18.x"

jobs:
 validate:
  name: Validate Changes
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Node.js
     uses: actions/setup-node@v4
     with:
      node-version: ${{ env.NODE_VERSION }}
      cache: "npm"

   - name: Install dependencies
     run: |
      npm ci
      npm run install:frontend
      npm run install:backend

   - name: Setup Prisma
     run: |
      cd backend
      npx prisma generate --schema=../prisma/schema.prisma

   - name: Lint frontend
     run: npm run lint --prefix frontend

   - name: Type check frontend
     run: |
      cd frontend
      npx tsc --noEmit

   - name: Test frontend
     run: npm run test:frontend
     env:
      CI: true

   - name: Test backend
     run: npm run test:backend
     env:
      CI: true
      DATABASE_URL: "file:./test.db"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

   - name: Security audit
     run: |
      npm audit --audit-level=moderate || true
      cd frontend && npm audit --audit-level=moderate || true
      cd ../backend && npm audit --audit-level=moderate || true
